Set ENV before executing payload.

diff --git a/vc3-builder b/vc3-builder
--- a/vc3-builder
+++ b/vc3-builder
@@ -11918,14 +11918,17 @@ sub cleanup {
                 unlink $self->sh_profile . '.prologue';
             }
 
+            if(-f $self->sh_profile . '.wrapper') {
+                unlink $self->sh_profile . '.wrapper';
+            }
+
             if(-f $self->sh_profile . '.payload') {
                 unlink $self->sh_profile . '.payload';
             }
         }
 
         $self->del_builder_variable('VC3_SH_PROFILE');
-        $self->del_builder_variable('VC3_SH_PROFILE_ENV');
-        $self->del_builder_variable('VC3_SH_PROFILE_PAYLOAD');
+        $self->del_builder_variable('VC3_SH_PROFILE_WRAPPER');
     }
 
     if($self->{child_pid}) {
@@ -12259,38 +12262,66 @@ sub order_variables {
 sub set_profile {
     my ($self, $profile_file, @command_and_args) = @_;
 
-    my ($env_file, $prog_file, $pay_file) = ($profile_file . '.env', $profile_file . '.prologue', $profile_file . '.payload');
+    my ($env_file, $prog_file, $wrap_file, $pay_file) = map { $profile_file . $_ } ('.env', '.prologue', '.wrapper', '.payload');
 
 
     # write to env file
     open(my $sh_f_env, '>', $env_file)
     || die "Could not open file $env_file $!";
-    print { $sh_f_env } "#! $shell\n\n";
+    print { $sh_f_env } <<EOFP;
+#! $shell\n\n
+
+# don't load environment variables repeatedly (e.g., to not grow PATH at every shell)
+if [ ! "\${VC3_ENV_TAG_GLOBAL}" = $$ ]
+then
+
+EOFP
     $self->set_environment_variables($sh_f_env);
+
+    print { $sh_f_env } <<EOFP;
+export VC3_ENV_TAG_GLOBAL=$$
+fi
+
+EOFP
+
     close($sh_f_env);
 
     # write to prologue file
     open(my $sh_f_prog, '>', $prog_file)
     || die "Could not open file $prog_file $!";
-    print { $sh_f_prog } "#! $shell\n\n";
-
     print { $sh_f_prog } <<EOFP;
-redirection=''
-if [ "\${VC3_INSIDE_WRAPPER_SCRIPT}" != yes ]
-then
-# if not inside the wrapper, we can't guarantee prologues work. Here we redirect all errors to /dev/null.
+#! $shell
 
-    redirection='2> /dev/null'
-fi
+# don't source prologues at a shell that already sourced them.
+if [ ! "\${VC3_ENV_TAG_LOCAL}" = $$ ]
+then
 
 EOFP
 
     for my $prog_line (@{$self->consolidate_prologue}) {
-        print { $sh_f_prog } "$prog_line \${redirection}";
+        print { $sh_f_prog } "$prog_line 2> /dev/null";
         print { $sh_f_prog } "\n";
     }
 
-    print { $sh_f_prog } "\n";
+    print { $sh_f_prog } <<EOFP;
+
+    VC3_ENV_TAG_LOCAL=$$
+fi
+
+EOFP
+
+    # write to general profile
+    open(my $sh_f, '>', "$profile_file")
+    || die "Could not open file $profile_file $!";
+
+    print { $sh_f } <<EOFP;
+#! $shell
+
+. $env_file
+. $prog_file
+
+EOFP
+    close($sh_f);
 
     # write to payload file
     open(my $sh_f_pay, '>', $pay_file)
@@ -12302,35 +12333,31 @@ if [ "\${VC3_INSIDE_WRAPPER_SCRIPT}" != yes ]
 then
 
     echo This script cannot be executed by itself.
-    echo Run instead: ${profile_file}
+    echo Run instead: ${wrap_file}
     exit 1
 fi
 
+export ENV=$profile_file
+
 EOFP
 
-    print { $sh_f_pay } 'cw="$(readlink -f $( cd "$( dirname "$0" )" && pwd ))"';
-    print { $sh_f_pay } "\n\n";
-    print { $sh_f_pay } '. $cw/' . basename($prog_file) . "\n\n";
-
-
-    print { $sh_f_pay } join(' ', @command_and_args);
+    print { $sh_f_pay } join(' ', 'exec', @command_and_args);
     print { $sh_f_pay } "\n";
 
     close($sh_f_pay);
     chmod 0755, $pay_file;
 
     # write to wrapper file
-    open(my $sh_f, '>', "$profile_file")
-    || die "Could not open file $profile_file $!";
+    open(my $sh_f_wrap, '>', "$wrap_file")
+    || die "Could not open file $wrap_file $!";
 
-    print { $sh_f } "#! $shell\n\n\n";
-    print { $sh_f } 'cw="$(readlink -f $( cd "$( dirname "$0" )" && pwd ))"';
-    print { $sh_f } "\n\n";
-    print { $sh_f } '. $cw/' . basename($env_file) . "\n\n";
-    print { $sh_f } "export VC3_INSIDE_WRAPPER_SCRIPT=yes\n\n";
-    print { $sh_f } q(cd  "${HOME}") . "\n\n";
+    print { $sh_f_wrap } "#! $shell\n\n\n";
+    print { $sh_f_wrap } "\n\n";
+    print { $sh_f_wrap } ". $env_file \n\n";
+    print { $sh_f_wrap } "export VC3_INSIDE_WRAPPER_SCRIPT=yes\n\n";
+    print { $sh_f_wrap } q(cd  "${HOME}") . "\n\n";
 
-    my $payload = '$cw/' . basename($pay_file);
+    my $payload = $pay_file;
 
     my $env = $self->active_widgets();
     if($self->plan and $self->plan->order) {
@@ -12350,15 +12377,13 @@ EOFP
         }
     }
 
-    print { $sh_f } "exec $payload\n\n";
+    print { $sh_f_wrap } "exec $payload\n\n";
 
-    close($sh_f);
-    chmod 0755, $profile_file;
+    close($sh_f_wrap);
+    chmod 0755, $wrap_file;
 
-    $self->add_builder_variable('VC3_SH_PROFILE', $profile_file);
-    $self->add_builder_variable('VC3_SH_PROFILE_ENV', $env_file);
-    $self->add_builder_variable('VC3_SH_PROFILE_PROLOGUE', $prog_file);
-    $self->add_builder_variable('VC3_SH_PROFILE_PAYLOAD', $pay_file);
+    $self->add_builder_variable('VC3_SH_PROFILE',         $profile_file);
+    $self->add_builder_variable('VC3_SH_PROFILE_WRAPPER', $wrap_file);
 }
 
 sub consolidate_prologue {
@@ -12411,7 +12436,7 @@ sub execute {
             '/usr/bin/env',
             '-i',
             $self->preserved_vars(),
-            $self->sh_profile);
+            $self->sh_profile . '.wrapper');
 
         POSIX::setpgid(0, 0);
 
@@ -12462,7 +12487,7 @@ sub shell {
             '/usr/bin/env',
             '-i',
             $self->preserved_vars(),
-            $self->sh_profile);
+            $self->sh_profile . '.wrapper');
         exec { $args[0] } @args;
         die 'Could not exec shell';
     } elsif($pid > 0) {
